export interface Painting {
  id: string;
  title: string;
  description: string;
  price: number;
  dimensions: string;
  medium: string;
  year: number;
  category: string; // Medium type: Painting, Photography, Sculpture, Drawing, Mixed Media
  style: string; // Artistic style: Abstract, Landscape, Portrait, Still Life, Urban, Contemporary, etc.
  image: string;
  available: boolean;
  isPreOrder?: boolean;
  preOrderReleaseDate?: string;
  preOrderDiscount?: number;
  artistId?: string;
  artist?: string;
}

export const paintings: Painting[] = [
  {
    id: "1",
    title: "Dawn of Hope",
    description: "A piece that expresses the rebirth of hope through warm colors and fluid forms.",
    price: 1200,
    dimensions: "80x60 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Painting",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    available: true,
  },
  {
    id: "2",
    title: "Silence of the Night",
    description: "An exploration of the tranquility and mystery of night through blue and violet tones.",
    price: 1500,
    dimensions: "100x80 cm",
    medium: "Acrylic on canvas",
    year: 2024,
    category: "Painting",
    style: "Contemporary",
    image: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&q=80",
    available: true,
  },
  {
    id: "3",
    title: "Mountain Path",
    description: "A stunning view of mountain trails with the light of sunset.",
    price: 2000,
    dimensions: "120x90 cm",
    medium: "Oil on canvas",
    year: 2023,
    category: "Painting",
    style: "Landscape",
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&q=80",
    available: true,
  },
  {
    id: "4",
    title: "Portrait in Shadow",
    description: "A deep study of human emotions through chiaroscuro technique.",
    price: 1800,
    dimensions: "70x50 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Painting",
    style: "Baroque",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    available: false,
  },
  {
    id: "5",
    title: "Ocean Waves",
    description: "The power and beauty of the sea captured in a dynamic moment.",
    price: 1400,
    dimensions: "90x70 cm",
    medium: "Acrylic on canvas",
    year: 2024,
    category: "Photography",
    style: "Landscape",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=80",
    available: true,
  },
  {
    id: "6",
    title: "Spring Flowers",
    description: "The beauty of spring expressed through wild flowers.",
    price: 900,
    dimensions: "60x50 cm",
    medium: "Watercolor",
    year: 2024,
    category: "Painting",
    style: "Still Life",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&q=80",
    available: true,
  },
  {
    id: "7",
    title: "The Old City",
    description: "Narrow streets and traditional architecture of historic towns.",
    price: 2500,
    dimensions: "150x100 cm",
    medium: "Oil on canvas",
    year: 2023,
    category: "Painting",
    style: "Urban",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80",
    available: true,
  },
  {
    id: "8",
    title: "Abstraction I",
    description: "Experimentation with geometric shapes and contrasting colors.",
    price: 1100,
    dimensions: "80x80 cm",
    medium: "Mixed media",
    year: 2024,
    category: "Mixed Media",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&q=80",
    available: true,
  },
  {
    id: "9",
    title: "Golden Hour",
    description: "A mesmerizing capture of the fleeting moments when sunlight paints the world in warm amber tones.",
    price: 1650,
    dimensions: "100x70 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Photography",
    style: "Landscape",
    image: "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800&q=80",
    available: true,
  },
  {
    id: "10",
    title: "Inner Reflection",
    description: "An introspective piece exploring the depths of human consciousness through abstract forms.",
    price: 1350,
    dimensions: "90x90 cm",
    medium: "Acrylic on canvas",
    year: 2024,
    category: "Painting",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80",
    available: true,
  },
  {
    id: "11",
    title: "Autumn Dreams",
    description: "A vivid portrayal of autumn's warmth through rich golden and crimson hues, capturing the fleeting beauty of falling leaves.",
    price: 1750,
    dimensions: "110x85 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Painting",
    style: "Impressionist",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    available: true,
  },
  {
    id: "12",
    title: "Cosmic Dance",
    description: "An explosive celebration of color and movement, inspired by the celestial ballet of stars and galaxies.",
    price: 2100,
    dimensions: "130x95 cm",
    medium: "Mixed media",
    year: 2024,
    category: "Mixed Media",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    available: true,
  },
  {
    id: "13",
    title: "Misty Morning",
    description: "A serene landscape capturing the quiet beauty of dawn breaking through morning mist.",
    price: 1450,
    dimensions: "95x75 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Painting",
    style: "Impressionist",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    available: true,
  },
  {
    id: "14",
    title: "Urban Pulse",
    description: "Dynamic composition reflecting the energy and rhythm of modern city life.",
    price: 1900,
    dimensions: "100x100 cm",
    medium: "Acrylic on canvas",
    year: 2024,
    category: "Painting",
    style: "Contemporary",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    available: true,
  },
  {
    id: "15",
    title: "Desert Sunset",
    description: "Breathtaking view of the sun setting over endless sand dunes, painted in warm ochre and violet tones.",
    price: 1650,
    dimensions: "120x80 cm",
    medium: "Oil on canvas",
    year: 2023,
    category: "Photography",
    style: "Landscape",
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
    available: true,
  },
  {
    id: "16",
    title: "Fragmented Reality",
    description: "A bold exploration of perception through geometric abstraction and vibrant color contrasts.",
    price: 1550,
    dimensions: "85x85 cm",
    medium: "Mixed media",
    year: 2024,
    category: "Mixed Media",
    style: "Contemporary",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80",
    available: true,
  },
  {
    id: "17",
    title: "Garden Symphony",
    description: "A celebration of nature's diversity through a vibrant arrangement of botanical elements.",
    price: 1100,
    dimensions: "70x60 cm",
    medium: "Watercolor",
    year: 2024,
    category: "Drawing",
    style: "Still Life",
    image: "https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=800&q=80",
    available: true,
  },
  {
    id: "18",
    title: "Midnight Blues",
    description: "An emotional journey through deep blues and purples, evoking the mystery of night.",
    price: 1850,
    dimensions: "110x90 cm",
    medium: "Oil on canvas",
    year: 2024,
    category: "Painting",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    available: true,
  },
  {
    id: "19",
    title: "Ancient Paths",
    description: "Historical cobblestone streets winding through time-worn architecture.",
    price: 2200,
    dimensions: "140x105 cm",
    medium: "Oil on canvas",
    year: 2023,
    category: "Painting",
    style: "Realism",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&q=80",
    available: true,
  },
  {
    id: "20",
    title: "Serene Waters",
    description: "Tranquil lakeside scene capturing the perfect stillness of a calm summer day.",
    price: 1700,
    dimensions: "105x80 cm",
    medium: "Acrylic on canvas",
    year: 2024,
    category: "Painting",
    style: "Landscape",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    available: true,
  },
  {
    id: "21",
    title: "Celestial Dreams",
    description: "An upcoming masterpiece exploring cosmic beauty through vibrant nebula-inspired colors. Pre-order now for exclusive early access.",
    price: 2800,
    dimensions: "150x120 cm",
    medium: "Mixed media on canvas",
    year: 2025,
    category: "Painting",
    style: "Abstract",
    image: "https://images.unsplash.com/photo-1556139966-56c3df1ddc63?w=800&q=80",
    available: false,
    isPreOrder: true,
    preOrderReleaseDate: "2025-03-15",
    preOrderDiscount: 15,
    artist: "Lamiart",
    artistId: "1",
  },
  {
    id: "22",
    title: "Urban Symphony",
    description: "A breathtaking cityscape capturing the rhythm and energy of metropolitan life. Limited pre-order edition with special pricing.",
    price: 2400,
    dimensions: "130x100 cm",
    medium: "Oil on canvas",
    year: 2025,
    category: "Painting",
    style: "Contemporary",
    image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&q=80",
    available: false,
    isPreOrder: true,
    preOrderReleaseDate: "2025-02-28",
    preOrderDiscount: 20,
    artist: "Marco Rossi",
    artistId: "2",
  },
  {
    id: "23",
    title: "Whispers of Spring",
    description: "Delicate floral composition celebrating the rebirth of nature. Pre-order to secure this exclusive piece before public release.",
    price: 1900,
    dimensions: "90x70 cm",
    medium: "Watercolor on paper",
    year: 2025,
    category: "Painting",
    style: "Impressionist",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&q=80",
    available: false,
    isPreOrder: true,
    preOrderReleaseDate: "2025-04-01",
    preOrderDiscount: 10,
    artist: "Sofia Chen",
    artistId: "3",
  },
  {
    id: "24",
    title: "Digital Horizons",
    description: "Cutting-edge digital art piece merging traditional techniques with modern technology. Pre-order exclusive with certificate of authenticity.",
    price: 3200,
    dimensions: "120x120 cm",
    medium: "Digital print on canvas",
    year: 2025,
    category: "Photography",
    style: "Contemporary",
    image: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&q=80",
    available: false,
    isPreOrder: true,
    preOrderReleaseDate: "2025-03-30",
    preOrderDiscount: 25,
    artist: "Lamiart",
    artistId: "1",
  },
];

export const categories = Array.from(new Set(paintings.map((p) => p.category)));

// Get unique styles and sort with Baroque first
const uniqueStyles = Array.from(new Set(paintings.map((p) => p.style)));
export const styles = uniqueStyles.sort((a, b) => {
  if (a === "Baroque") return -1;
  if (b === "Baroque") return 1;
  return a.localeCompare(b);
});

export function getPaintingById(id: string): Painting | undefined {
  return paintings.find((p) => p.id === id);
}

export function getPaintingsByCategory(category: string): Painting[] {
  return paintings.filter((p) => p.category === category);
}

export function getPaintingsByStyle(style: string): Painting[] {
  return paintings.filter((p) => p.style === style);
}
